module NumDecouvertePersonnalite
  module Nature
    VOYELLE: Symbol
    CONSONNE: Symbol
    TOUT: Symbol
    ALL: Array[Symbol]
  end
  MAITRE_NOMBRE: Hash[Integer, String]
  NOMBRE: Hash[Integer, String]
  NOMBRE_KARMIQUE: Hash[Integer, String]
  OCTAVE: Hash[Integer, String]
  TOUS_LES_NOMBRES: Hash[Integer, String]
  VERSION: String
  VALEURS: Hash[String, Integer]
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  def self.extract_niveau: -> Array[Integer]

  def self.generate_octave: -> Hash[Integer, String]

  def self.separate: (String) -> Array[String]
  def self.valeur_lettre: (String) -> Integer?
end
