module NumDecouvertePersonnalite
  OCTAVE: Hash[Integer, String]
  VERSION: String
  VALEURS: Hash[String, Integer]
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  def self.separate: (String) -> Array[String]
  def self.valeur_lettre: (String) -> Integer?
end
